### ISSUE TITLE
这两天惊现跑着跑着Logging error怎么解决呀，抢到的老哥有遇到没

### ISSUE THREAD

**Issue by shuweichen279** [ChinaVolvocars/jd_maotai_seckill#123]
--- Logging error ---
Traceback (most recent call last):
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 363, in _seckill
    self.submit_seckill_order()
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 593, in submit_seckill_order
    resp = self.session.post(
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/venv/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/venv/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/venv/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/venv/lib/python3.8/site-packages/requests/sessions.py", line 166, in resolve_redirects
    raise TooManyRedirects('Exceeded {} redirects.'.format(self.max_redirects), response=resp)
requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/py38/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/opt/anaconda3/envs/py38/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/opt/anaconda3/envs/py38/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/opt/anaconda3/envs/py38/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/envs/py38/lib/python3.8/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/opt/anaconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py38/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py38/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 314, in new_func
    return func(self, *args, **kwargs)
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 330, in seckill
    self._seckill()
  File "/Users/wayne/Downloads/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 365, in _seckill
    logger.info('抢购发生异常，稍后继续执行！', e)
Message: '抢购发生异常，稍后继续执行！'
Arguments: (TooManyRedirects('Exceeded 30 redirects.'),)

**Comment by JianLin176** [comment]
+1，用了两天，都有这个log

**Comment by yeahydq** [comment]
+1
