### ISSUE TITLE
Mac运行main.py各种错误, 一次都没运行成功过

### ISSUE THREAD

**Issue by chibofeng** [ChinaVolvocars/jd_maotai_seckill#146]
1. 配置已经更改好后, 运行直接提示
File "main.py", line 17
SyntaxError: Non-ASCII character '\xe5' in file main.py on line 18, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

【解决办法】

在Python源文件的最开始一行，加入一句：

# coding=UTF-8（等号换为”:“也可以）

或者

# -*- coding:UTF-8 -*-

2. 然后各种函数报错....

**Comment by ynpl** [comment]
兄弟 看看你的python 的版本

**Comment by ynpl** [comment]
先升级完python 再说

**Comment by chibofeng** [comment]
最新的3.9.1

**Comment by ynpl** [comment]
你从控制台打出来看看 python -V

**Comment by ynpl** [comment]
昨天我也遇到这个问题了 后来费心我的python版本不对  mac是自带python的你需要卸载之前的版本 然后替换新的版本

**Comment by chibofeng** [comment]
<img width="1109" alt="图片" src="https://user-images.githubusercontent.com/12591866/103618691-5a4ca700-4f6b-11eb-85c3-5cea6249f11e.png">
执行完后旧版python 依然存在

**Comment by ynpl** [comment]
> <img alt="图片" width="1109" src="https://user-images.githubusercontent.com/12591866/103618691-5a4ca700-4f6b-11eb-85c3-5cea6249f11e.png">
> 
> 执行完后旧版python 依然存在

是版本不多吧! 你在多找找这个教程不行换一个

**Comment by chibofeng** [comment]
1. 必须卸载2.7版本再安装新版本?  如果直接运行python3 mian.py不可以?
2. python3.x有没有具体版本的限制?
3. python 安装好后运行代码还会不会出现什么错误之类的?

**Comment by kyirving** [comment]
> 1. 必须卸载2.7版本再安装新版本?  如果直接运行python3 mian.py不可以?
> 2. python3.x有没有具体版本的限制?
> 3. python 安装好后运行代码还会不会出现什么错误之类的?

python3应该是可以的，我就是这样运行的，可能是pip下载三方类库的问题，默认pip好像是下到了mac默认python2.*版本中

**Comment by chibofeng** [comment]
已经知道是什么原因了
python3对应的应该用pip3来安装依赖工具, 如果直接运行源码中的"pip install -r requirements.txt" 则默认是安装的Python2.7的版本, 这样就会出现不兼容的情况, 也就是那些警告之类的
应该是运行 $pip3 install -r requirements.txt (安装完python3后, 需要单独安装pip3)安装依赖, 然后python3 main.py.这样源文件.py就可以直接运行了

**Comment by shuaixin** [comment]
你现在可以正常运行main.py了吗?我的怎么还是报错啊

**Comment by chibofeng** [comment]
> 你现在可以正常运行main.py了吗?我的怎么还是报错啊
可以正常运行了, 你那报什么错

**Comment by shuaixin** [comment]
> > 你现在可以正常运行main.py了吗?我的怎么还是报错啊
> > 可以正常运行了, 你那报什么错
你看看,就是下面这些
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 789, in get
    value = d[option]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 898, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/__init__.py", line 890, in __missing__
    raise KeyError(key)
KeyError: 'sku_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXX/Desktop/jd_maotai_seckill-master/main.py", line 23, in <module>
    jd_seckill = JdSeckill()
  File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 276, in __init__
    self.sku_id = global_config.getRaw('config', 'sku_id')
  File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/config.py", line 19, in getRaw
    return self._configRaw.get(section, name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'sku_id' in section: 'config'

**Comment by chibofeng** [comment]
> > > 你现在可以正常运行main.py了吗?我的怎么还是报错啊
> > > 可以正常运行了, 你那报什么错
> 
> 你看看,就是下面这些
> Traceback (most recent call last):
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 789, in get
> value = d[option]
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/**init**.py", line 898, in **getitem**
> return self.**missing**(key) # support subclasses that define **missing**
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/**init**.py", line 890, in **missing**
> raise KeyError(key)
> KeyError: 'sku_id'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/Users/XXXX/Desktop/jd_maotai_seckill-master/main.py", line 23, in
> jd_seckill = JdSeckill()
> File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 276, in **init**
> self.sku_id = global_config.getRaw('config', 'sku_id')
> File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/config.py", line 19, in getRaw
> return self._configRaw.get(section, name)
> File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 792, in get
> raise NoOptionError(option, section)
> configparser.NoOptionError: No option 'sku_id' in section: 'config'

这个还真没有遇到过, 基本步骤就是安装python3, 哪个版本都可以然后在更改默认启动的软连接, 这样就是为了启动时启动的是python3版本, 而不是2.7版本, 然后执行$pip3 install -r requirements.txt, 而不是$pip install -r requirements.txt, 安装依赖工具, 然后配置那两个id信息,启动main.py, python3 main.py  我这就可以正常运行了

**Comment by shuaixin** [comment]
> > > > 你现在可以正常运行main.py了吗?我的怎么还是报错啊
> > > > 可以正常运行了, 你那报什么错
> > 
> > 
> > 你看看,就是下面这些
> > Traceback (most recent call last):
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 789, in get
> > value = d[option]
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/**init**.py", line 898, in **getitem**
> > return self.**missing**(key) # support subclasses that define **missing**
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/collections/**init**.py", line 890, in **missing**
> > raise KeyError(key)
> > KeyError: 'sku_id'
> > During handling of the above exception, another exception occurred:
> > Traceback (most recent call last):
> > File "/Users/XXXX/Desktop/jd_maotai_seckill-master/main.py", line 23, in
> > jd_seckill = JdSeckill()
> > File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 276, in **init**
> > self.sku_id = global_config.getRaw('config', 'sku_id')
> > File "/Users/XXXX/Desktop/jd_maotai_seckill-master/maotai/config.py", line 19, in getRaw
> > return self._configRaw.get(section, name)
> > File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 792, in get
> > raise NoOptionError(option, section)
> > configparser.NoOptionError: No option 'sku_id' in section: 'config'
> 
> 这个还真没有遇到过, 基本步骤就是安装python3, 哪个版本都可以然后在更改默认启动的软连接, 这样就是为了启动时启动的是python3版本, 而不是2.7版本, 然后执行$pip3 install -r requirements.txt, 而不是$pip install -r requirements.txt, 安装依赖工具, 然后配置那两个id信息,启动main.py, python3 main.py 我这就可以正常运行了

你说的那个"更改默认启动的软连接"是怎么更改的????卸载Mac自带的2.7版本??????我是用pyCharm运行的main.py

**Comment by chibofeng** [comment]
自带的2.7版本好像卸载不了, 感觉那个软连接也没什么用, 你在终端里面运行python -V, 应该是输出2.7.x, python3 -V, 应该是输出3.x这样就对了, 然后运行main.py, $python3 main.py 试一下

**Comment by shuaixin** [comment]
> 自带的2.7版本好像卸载不了, 感觉那个软连接也没什么用, 你在终端里面运行python -V, 应该是输出2.7.x, python3 -V, 应该是输出3.x这样就对了, 然后运行main.py, $python3 main.py 试一下

好的,多谢哈,辛苦了!
