### ISSUE TITLE
how to fix this issue

### ISSUE THREAD

**Issue by xuanxuan2204** [ChinaVolvocars/jd_maotai_seckill#17]
Traceback (most recent call last):
  File "C:\Users\16384\Desktop\jd_maotai_seckill-master\main.py", line 2, in <module>
    from jd_spider_requests import JdSeckill
  File "C:\Users\16384\Desktop\jd_maotai_seckill-master\jd_spider_requests.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by tubesummer** [comment]
请问怎么解决的
