### ISSUE TITLE
二维码登录失败

### ISSUE THREAD

**Issue by Stanleyey** [ChinaVolvocars/jd_maotai_seckill#77]
请问作者大佬， 二维码登录失败是怎么回事呢? config.ini里该填的信息都填了啊，eid和fp也填写了，然后总是出下面这个错误：
2021-01-04 10:45:46,830 - 11204-MainThread - I:\Programs\jd_maotai_seckill-master\maotai\jd_spider_requests.py[line:208] - INFO: Code: 202, Message: 请手机客户端确认登录
2021-01-04 10:45:48,903 - 11204-MainThread - I:\Programs\jd_maotai_seckill-master\maotai\jd_spider_requests.py[line:211] - INFO: 已完成手机客户端确认
2021-01-04 10:45:49,078 - 11204-MainThread - I:\Programs\jd_maotai_seckill-master\maotai\jd_spider_requests.py[line:265] - INFO: 二维码登录成功
Traceback (most recent call last):
  File "I:\Programs\jd_maotai_seckill-master\main.py", line 28, in <module>
    jd_seckill.seckill_by_proc_pool()
  File "I:\Programs\jd_maotai_seckill-master\maotai\jd_spider_requests.py", line 313, in new_func
    self.login_by_qrcode()
  File "I:\Programs\jd_maotai_seckill-master\maotai\jd_spider_requests.py", line 302, in login_by_qrcode
    raise SKException("二维码登录失败！")
error.exception.SKException: 二维码登录失败！

先谢过大佬了，您和所有的贡献者都好给力啊！

**Comment by yanzhen1031** [comment]
海外服务器?

**Comment by Stanleyey** [comment]
> 海外服务器?

不是啊，梯子开不开都是这样的。

**Comment by Stanleyey** [comment]
解决了，把狗东的手机验证码登录web端的关掉就好了
