### ISSUE TITLE
大佬帮忙看下这个错误

### ISSUE THREAD

**Issue by googooog** [ChinaVolvocars/jd_maotai_seckill#83]
Traceback (most recent call last):
  File "/Users/sy/Desktop/jd_maotai_seckill-master/main.py", line 3, in <module>
    from maotai.jd_spider_requests import JdSeckill
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 12, in <module>
    from maotai.jd_logger import logger
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/jd_logger.py", line 24, in <module>
    set_logger()
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/jd_logger.py", line 18, in set_logger
    file_handler = logging.handlers.RotatingFileHandler(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 153, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding=encoding,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1142, in __init__
    StreamHandler.__init__(self, self._open())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1171, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/Users/jd_seckill.log'

提示以上的错误，是什么问题啊

**Comment by cc2cc** [comment]
没权限写log文件，把目录权限设置可写吧

**Comment by googooog** [comment]
> 没权限写log文件，把目录权限设置可写吧

谢谢，改完权限了，还是有错误，帮忙看下

Traceback (most recent call last):
  File "/Users/sy/Desktop/jd_maotai_seckill-master/main.py", line 3, in <module>
    from maotai.jd_spider_requests import JdSeckill
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/jd_spider_requests.py", line 13, in <module>
    from maotai.timer import Timer
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/timer.py", line 8, in <module>
    from maotai.config import global_config
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/config.py", line 22, in <module>
    global_config = Config()
  File "/Users/sy/Desktop/jd_maotai_seckill-master/maotai/config.py", line 9, in __init__
    raise FileNotFoundError("No such file: config.ini")
FileNotFoundError: No such file: config.ini

**Comment by cc2cc** [comment]
这不写着呢嘛
No such file: config.ini
没有config.ini配置文件

**Comment by googooog** [comment]
> 这不写着呢嘛
> No such file: config.ini
> 没有config.ini配置文件

有配置文件啊，都放在下载的同一个文件夹里了
