### ISSUE TITLE
抢到了感谢大佬

### ISSUE THREAD

**Issue by ySirius** [ChinaVolvocars/jd_maotai_seckill#9]
抢到了感谢大佬

**Comment by scholar-fuck** [comment]
详细说说咋操作的呗，应该具体什么时间运行main.py然后点击1或2呢

**Comment by shengchaojie** [comment]
额 说下说下

**Comment by chenlongCc** [comment]
> 详细说说咋操作的呗，应该具体什么时间运行main.py然后点击1或2呢

十点之前，预约过之后 选2就完事了 这个人有点恶心了 人家作者都给删了 他直接搬过来

**Comment by shengchaojie** [comment]
> > 详细说说咋操作的呗，应该具体什么时间运行main.py然后点击1或2呢
> 
> 十点之前，预约过之后 选2就完事了 这个人有点恶心了 人家作者都给删了 他直接搬过来

还好搬了。不然我找不到了。

**Comment by abrams24** [comment]
Traceback (most recent call last):
  File "D:\Anaconda\envs\maotai\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Anaconda\envs\maotai\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda\envs\maotai\lib\concurrent\futures\process.py", line 295, in _queue_management_worker
    shutdown_worker()
  File "D:\Anaconda\envs\maotai\lib\concurrent\futures\process.py", line 253, in shutdown_worker
    call_queue.put_nowait(None)
  File "D:\Anaconda\envs\maotai\lib\multiprocessing\queues.py", line 129, in put_nowait
    return self.put(obj, False)
  File "D:\Anaconda\envs\maotai\lib\multiprocessing\queues.py", line 83, in put
    raise Full
queue.Full

这个是怎么回事？

**Comment by Xzw111222** [comment]
之前我用原项目都才一百多个star。好家伙现在六千多个，这个月抢了4瓶

**Comment by liangch888** [comment]
> 抢到了感谢大佬

请问eid和fp怎么获取的，我抓包怎么都没发现，是哪个接口呢，请告知

**Comment by sunwenli** [comment]
抢了八瓶的路过 😈

**Comment by roamerop** [comment]
> 抢了八瓶的路过 😈

老哥，手机和脚本可以同时抢吗。还有我没有会员，他这个脚本也显示预约成功了

**Comment by Clearlove0u0** [comment]
> Traceback (most recent call last):
> File "D:\Anaconda\envs\maotai\lib\threading.py", line 916, in _bootstrap_inner
> self.run()
> File "D:\Anaconda\envs\maotai\lib\threading.py", line 864, in run
> self._target(*self._args, **self._kwargs)
> File "D:\Anaconda\envs\maotai\lib\concurrent\futures\process.py", line 295, in _queue_management_worker
> shutdown_worker()
> File "D:\Anaconda\envs\maotai\lib\concurrent\futures\process.py", line 253, in shutdown_worker
> call_queue.put_nowait(None)
> File "D:\Anaconda\envs\maotai\lib\multiprocessing\queues.py", line 129, in put_nowait
> return self.put(obj, False)
> File "D:\Anaconda\envs\maotai\lib\multiprocessing\queues.py", line 83, in put
> raise Full
> queue.Full
> 
> 这个是怎么回事？

升级python3.9

**Comment by cjhroyal** [comment]
抢到+1 哈哈

**Comment by shengchaojie** [comment]
> 抢了八瓶的路过 😈

你这是有几个号？

**Comment by xing9133** [comment]
二维码登陆不了，这个是怎么解决的
